---
- hosts: localhost  # Assuming you have your target hosts defined in your inventory
  connection: local
  become: true  # Assuming you need elevated privileges for package installation

  pre_tasks:
    - name: update repositories
    apt:
      update_cache: yes
      changed_when: False
  tasks:
    - include: tasks/packages.yml
