---
- hosts: localhost  # Assuming you have your target hosts defined in your inventory
  connection: local
  become: true  # Assuming you need elevated privileges for package installation

  pre_tasks:
    - name: Update repositories
      apt:
        update_cache: yes
        changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
