---
- hosts: localhost  # Assuming you have your target hosts defined in your inventory
  connection: local
  become: true  # Assuming you need elevated privileges for package installation

  tasks:
    - name: Install packages
      apt:
        name: 
              - htop
              - mc
              - tmux
        state: present  # You can add state: present to explicitly install the package
