- name: first play
  hosts: all
  gather_facts: false
  tasks:
    - name: update apt repo
      ansible.builtin.apt:
        update_cache: yes
      tags: always
    
    - name: install initial packages for db
      ansible.builtin.apt:
        name: dirmngr
        state: present
      tags: v15

    - name: update apt repo
      ansible.builtin.shell:
        cmd: ls -l | grep log  
      tags: always

    - name: update apt repo
      ansible.builtin.apt:
        name: apache2
        state: present
      tags: always

    - name: install initial packages for db
      ansible.builtin.apt:
        name: lsb-release
        state: present  
      tags: v15

    - name: install initial packages for db
      ansible.builtin.apt:
        name: postgresql-15
        state: present
      tags: v15    

    - name: install initial packages for db
      ansible.builtin.apt:
        name: postgresql-14
        state: present
      tags: v14

    - name: install initial packages for db
      ansible.builtin.apt:
        name: postgresql-client-14
        state: present
      tags: v14

- name: sec play for webserver
  hosts: web_servers
  gather_facts: false
  tasks:
    - name: update apt repo 
      ansible.builtin.apt:
        name: apache2
        state: present
      tags: web

    - name: run apache
      ansible.builtin.service:
        name: apache2
        enabled: yes
        state: present
      tags: web  

    - name: copy remote file
      ansible.builtin.copy:
        src: /srv/myfiles/foo.conf
        dest: /etc/ansible.conf
        owner: ansible
        group: sudoers
        mode: u+rw,g-wx,o-rwx
      tags: web
